base_url = "https://archjh.github.io"

title = "archjh的个人博客"
description = "A timeless blog theme"
compile_sass = false
highlight_code = true
generate_rss = true

[extra]
henry_links = [
    {url = "about", name = "About"},
]
henry_github = "https://github.com/sirodoht/zola-henry"
henry_twitter = "https://twitter.com/jekyllrb"
